services:
  - type: web
    name: ai-prompt-generator
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn prompt_generator.wsgi:application"
    envVars:
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: prompt-generator-db
          property: connectionString

databases:
  - name: prompt-generator-db
    databaseName: prompt_generator
    user: prompt_generator 