# Generated by Django 5.1 on 2025-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='related_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated related keywords or synonyms'),
        ),
    ]
